kind: pipeline
name: default
type: docker

clone:
  depth: 50
  
steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go build

volumes:
- name: deps
  temp: {}